#spring:
#  sql:
#    init:
#      mode: always # Автоматически выполняет schema.sql и data.sql (если есть)
#      schema-locations: classpath:schema.sql

jwt:
  secret: BAz9u0TYx17C0iL/qhchIvfrpxR2NEW4uIsRUGSiUSpkEEEcw81W/4co64ZDI/xmPWW29EvpGi28xbJSG/vgyw==
  access:
    expiration: 259200000  # 3 дня в миллисекундах (3 * 24 * 60 * 60 * 1000)
  refresh:
    expiration: 604800000  # 7 дней в миллисекундах (7 * 24 * 60 * 60 * 1000)
logging:
  level:
    org.springframework: info
    com.yourpackage: debug